version: 2
jobs:
  build:
    working_directory: ~/hullabatool
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ arch }}-{{ .Branch}}-{{ checksum "yarn.lock" }}
            - dependency-cache-{{ arch }}-{{ .Branch}}
            - dependency-cache
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch}}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn test
